### ISSUE TITLE
Solutions section

### ISSUE THREAD

**Issue by MatiasOS** [windingtree/homepage#103]
**Is your feature request related to a problem? Please describe.**
 We need a component that show solutions section.

**Describe the solution you'd like**
Create one or more components that help to show solution section inside of suppliers view.

**Additional context**
View : [Supliers](https://windingtree.com/suppliers.html)
Part of #70
![solutions-00](https://user-images.githubusercontent.com/5481398/49308674-be146400-f4b7-11e8-9323-9c7604e6f36e.png)

**Comment by menschikov** [comment]
@MatiasOS please check #92 , just fyi
