### ISSUE TITLE
Key benefits

### ISSUE THREAD

**Issue by MatiasOS** [windingtree/homepage#106]
**Is your feature request related to a problem? Please describe.**
Create a KeyBenefits Component. This component is used in Sellers and Suppliers pages

**Describe the solution you'd like**
We need a component that will be used in both pages.

**Additional context**
Related to #91 

![keybenefits](https://user-images.githubusercontent.com/5481398/49466728-8a02b100-f7df-11e8-9c5a-7bc98db07cb4.png)

![keybenefits-01](https://user-images.githubusercontent.com/5481398/49467086-612eeb80-f7e0-11e8-8bf7-e65def314a89.png)

**Comment by menschikov** [comment]
@MatiasOS please see #91 same issues
