### ISSUE TITLE
Server Side Render

### ISSUE THREAD

**Issue by menschikov** [windingtree/homepage#119]
**Is your feature request related to a problem? Please describe.**
For SEO purposes we need enable Server Side Rendering for website. Best would be to deliver SSR version only to search robots.

**Describe the solution you'd like**
SSR

**Describe alternatives you've considered**
Isomorphic app is not that good with react

**Comment by menschikov** [comment]
@PabloAlice,
the best option is to check useragent and route search bots to SSR version of website, and humans should be router to usuall SPA

here's best description of this https://www.christianoliveira.com/blog/en/seo-progressive-web-apps-pwa/

**Comment by menschikov** [comment]
@PabloAlice we also need to exclude all js from prerendered ages for search robots

**Comment by menschikov** [comment]
_Reminding issue:_ For SEO purposes we need to deliver search robots a static version of website . Best would be to deliver SSR version ONLY to search robots. 

@PabloAlice @MatiasOS so there are several options of using SSR:

REQUIREMENT FOR ALL OPTIONS: exclude scripts from static versions

**1. "Classic way":**
1. setup NGINX server in front of NODE server, to proxy requests
2. Nginx will define useragent and route robots to static version and humans to SPA (node server)
3. obviously we need some "worker" in React that will update static version when we push some changed
**_Pros:_** 
+ we don't need to modify app, but render static version with some external script and put it into folder. 
**_Cons:_** 
- I think we can't setup 2 servers Nginx and Node on now.sh. We need VPS for that

**2. React routing with Next.js:** 
create a HOC and check for user-agent and then accordingly use no-ssr tag from next.js
**_Pros:_**
+ efficient way
+ can be done on now.sh
+ because SSR will be presented only to robots we can skip visual bugs that will come during ssr
_**Cons:**_
- need to research next.js
- needs some app modification

**3. Full SSR for all useragents**
generate SSR version (with next.js) and deliver to all useragents
_**Pros**_
+ easier than in option 2, no defining of useragents needed
_**Cons**_
- need to research next.js
- need app modification to be perfect after SSR
- problems with analytics setup: static version require analytics settings that we can't prepare and test while SPA developing, basically scripts should be added to html pages after rendering. Maybe a solution would be just to add Google Tag manager tag
- we can't exclude scripts from version to robots because all useragents get same version

**4. "Tricky useragent routing":**
- serve static and SPA version from same Node server
- create sitemap.xml with all urls with parameter  ?ssr=true e.g. windingtree.com?ssr=true
- robots go through website using this sitemap
- when Node server gets request for url with ?ssr=true (it means robot came) it replies with SSR version, otherwise with SPA
_**Pros**_
+ not sure if this is easier than option 2
+ can be done on now.sh
+ because SSR will be presented only to robots we can skip visual bugs that will come during ssr
_**Cons:**_
- there's a risk that search robot finds out that url with ?ssr=true and without it shows different pages (e.g. when we exclude scripts)
- needs some app modification

@kvbik @JirkaChadima @AugustoL maybe you have some thoughts, ideas, advices?

**Comment by PabloAlice** [comment]
Well, Next.js it's a nice option if we are at the beginning of the project, I don't think that we really need it.
First, I would make an SSR with React "natively".
https://medium.freecodecamp.org/demystifying-reacts-server-side-render-de335d408fe4
It's not a big deal.
Then, we can think about some optimizations, like filtering user-agents, adding Nginx, etc.

I think that the only advantage of filtering user-agents is taking off rendering weight to our server.
We shouldn't worry about it right now.

**Comment by menschikov** [comment]
@PabloAlice if we go with the way of SSR for all useragents we need to take care about next:
- avoid realtime render for every request, but have cached version of website and update it on every merged PR
- make sure Google Tag manager tag properly injected to every rendered page

**Comment by JirkaChadima** [comment]
If it's easy to maintain visual consistency for SSR, I'd go for SSR for everybody. If it's hell, I'd filter out crawlers and give SSR only to them. It's easier to do changes if you have to check only one version after every change (But SSR might work really well, I don't have much experience with that in React).

From my understanding, you need express.js for SSR anyway, so the filtering can be done in there, no need for nginx. We can inspire ourselves by [this package](https://github.com/prerender/prerender-node).
