### ISSUE TITLE
HackathonPage build

### ISSUE THREAD

**Issue by menschikov** [windingtree/homepage#124]
### Option 1: Look on this as on a separate product and create from scratch
We can look on hackathon page as on a separate product and create own backlog for it with dozens of user stories like e.g. "As a developer I want to browse challenges I will be offered to solve..." etc

We may need it to some new page/feature. But let's see on option 2.

### Option 2: Look on this task as on expanding/copying of proven solution for the same stories
Stories weren't changed since Prague Hackathon and we have clear and proven solution for that, the solution that satisfy stakeholders and product owner.
So there's just a task: _We need to create a landing page for Lisbon Hackathon as a copy of Prague Hackathon page but change content to fit Lisbon hackathon._ 
**We can cover all this with high-level user story:** "_As a hackathon manager I'm interested in having a landing page for my hackathon to attract partners, attendees, media and keep them up to date with Hackathon details"._ (maybe this is what we missing)
**Proposed Solution:** Save time on design and preparation and use proven solution from Prague Hackathon

________________________________________________________________________________________________

**tasks**
1. We need to attract partners, attendees, media to our Lisbon hackathon. We are interested in new attendees and partners, not only in those who is already in our community and mailing lists.
2. We need to allow all kind of participants to register to hackathon 
3. We need to provide attendees, partners and media a source where they can read actual information about event at any time.

**Proposed solution:**
A Landing Page with information about hackathon and ability for partners and attendees to register
_Deadline_: 25.02.2019

UX Requirements:
- Clear and sufficient information
  - General description of hackathon, Program, Venue, Dates, What to expect, Issues to solve, Prizes
  - Types of attendees and valuable offers for them
  - Information how to participate and types of participation
  - Information about Partners and offers for partners
  - Optional: Recap of previous hackathon
- Content and design should be attractive and fit target audience interests
- Clear and obvious CTA buttons and links 
- Short but sufficient registration form

Tech requirements:
- Webpage should be a part of windingtree.com - as a subpage 
- Webpage should be SEO-oriented
- Webpage should be shareable via social networks (open graph tags)
- Integrate google analytics to the page
- We can forward users to google form to register
- The page should be reusable for future events
- Editing of the content of the page should easy: without editing html directly and all content should be edited in one place
- It is possible to re-use previous hackathon page that stored in jekyll branch of repo or at least use it as a reference, because it has all required blocks and we can save time on dedsign (https://windingtree.com/winding-tree-hackathon-prague-2018 any commit before 24/10/18)

Reference:
![hacking the travel industry with blockchain solutions winding tree hackathon prague 2018](https://user-images.githubusercontent.com/4557491/51732382-ebd4ee00-209f-11e9-8e70-fdd34b4dc429.png)
Recommendation: current map should be replaced with new good-looking component. Requires Location component (#37) from wt-ui library

**Comment by skkr** [comment]
@menschikov we are going to keep the same content we have now?

**Comment by menschikov** [comment]
Yes

вт, 18 дек. 2018 г., 5:43 Nico Calabrese notifications@github.com:

**Comment by skkr** [comment]
Here is a design mockup to take as a reference. We have everything to build it in wt-ui.

![wp-hackathon-v4](https://user-images.githubusercontent.com/1435069/50460149-eb86ed00-0951-11e9-81ef-dfd256aaba13.jpg)

**Comment by PabloAlice** [comment]
Estimation: ~16hs
