### ISSUE TITLE
CommunityPage: Need to fix svg mask for collaborators slick

### ISSUE THREAD

**Issue by menschikov** [windingtree/homepage#135]
**Describe the bug**
need to fix svg mask

**To Reproduce**
1. Go to Contributors slick

**Screenshots**
http://joxi.ru/KAgxqB5i4By9vr

We need to create correct svg mask to look like here or if impossible - use rounded avatars.

can be done after launch

**Comment by skkr** [comment]
@menschikov is it wrong in wt-ui storybook?

**Comment by menschikov** [comment]
@skkr we need to adapt it for gh images. On new version we grab avatars from website (on current version I cropped them) and they dont fit the mask, see how it looks like.

**Comment by skkr** [comment]
@menschikov it would be much faster to fix making the source images the same size and aspect ratio than the ones used before. Can you try that?

**Comment by menschikov** [comment]
We can't do that anymore, Mati parses it from github and includes automatically. This is a way it should work, we will leave this for next iteration. not for now

**Comment by skkr** [comment]
Right, got it. Thanks for clarify :)

**Comment by skkr** [comment]
This is done, will be included in my next PR (UI-adjustments)
