### ISSUE TITLE
MainPage, SuppliersPage, SellersPage, VendorsPage: How It Works Diagram

### ISSUE THREAD

**Issue by skkr** [windingtree/homepage#137]
Make a design proposal to include "How it works" diagram in homepage

Then include it in the Main page and the Solutions section

**Comment by skkr** [comment]
@menschikov something like this? I advice to have a text close to the button.

In other pages we'll have to use the diagram between two sections with white background.

![image](https://user-images.githubusercontent.com/1435069/50353148-14f4e280-0526-11e9-96ea-dd7083bdbd24.png)

**Comment by menschikov** [comment]
Nice!

**Comment by menschikov** [comment]
But on solutions pages the diagram should be after benefits

**Comment by skkr** [comment]
Yes, great! 👍

**Comment by skkr** [comment]
Final image is attached. 

Layout reference is in my previous comment.

Background style is `.bg-light`, but it has a radial gradient so use these styles instead for this specific section.

```
background: radial-gradient(415.44px at 50% 50%, #FFFFFF 0%, #F2F2F2 100%);
box-shadow: 0 12px 20px rgba(0, 0, 0, 0.1);
```

<img width="1311" alt="hiw-diagram" src="https://user-images.githubusercontent.com/1435069/50356733-e2e97d80-0531-11e9-9b3c-174dc2ba1f87.png">
