### ISSUE TITLE
AllPages: footer

### ISSUE THREAD

**Issue by menschikov** [windingtree/homepage#143]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Create footer for all pages like https://windingtree.com/

DO NOT include Lif Token for now

@skkr guess we have it ready in framework, right? Post a link here please

**Comment by skkr** [comment]
@menschikov that's right

**Comment by menschikov** [comment]
@MatiasOS, @skkr  I see footer on now.sh, can we consider this as done and close the issue?
