### ISSUE TITLE
FondationPage: team section

### ISSUE THREAD

**Issue by menschikov** [windingtree/homepage#146]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Create React team section
Store content in JSON
![image](https://user-images.githubusercontent.com/4557491/50269665-d3dece80-0450-11e9-8ef6-4ea824d13ff0.png)

**Additional context**

**Comment by skkr** [comment]
*UI*
- [ ] Add user component to storybook docs.

**Comment by skkr** [comment]
This is ready for implementation in homepage 

[Info in Storybook](https://storybook-ef67b.firebaseapp.com/?selectedKind=Preset%20Blocks&selectedStory=User&full=0&addons=0&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel)
