### ISSUE TITLE
Frontend fixes

### ISSUE THREAD

**Issue by menschikov** [windingtree/homepage#160]
Pease see brach "content"

- [ ] 1. all links (buttons and links)  to external resources should be opened in new tab. I think we can extend component to check the passed prop

- [ ]  2. there's button Watch video in the main banned that should open video in modal

- [x] 3. Partner's logos and in the Press should be in one row (up to 6 logos in row)
![image](https://user-images.githubusercontent.com/4557491/50698737-50d88d80-1078-11e9-8256-e03e01c1759a.png)

- [x] 4. @skkr we need to fix this 
![image](https://user-images.githubusercontent.com/4557491/50725998-44683980-1139-11e9-8451-9c4e9dc48836.png)

- [x] 5. **REFACTOR ON NEXT ITERATION** @MatiasOS, about Event section, can we store image name as an object's property instead importing it? At least we can store in const='./images/' and concatinate it with string from Object, e.g imgSrc='éns.png'
![image](https://user-images.githubusercontent.com/4557491/50726095-d290ef80-113a-11e9-991d-bbb653eafb7b.png)

- [ ] 6. Menu should be transparent over Hero banner
![image](https://user-images.githubusercontent.com/4557491/50736243-95396a00-11ed-11e9-94e6-9ed84b751120.png)
![image](https://user-images.githubusercontent.com/4557491/50736247-9d91a500-11ed-11e9-8864-fa2786b9605b.png)

- [ ] 7. Nothing happens on "Learn more" click on cards in Top and Bottom banners. Link is filled in json

Solution: make whole card a link (<a>), cursor onHover "pointer", make "learn more" simple <p><u>. @skkr I would also make mobile view of this card like on current website (more compact and UX friendly)

- [ ]  8.1 check and fix all mobile views:  need space between buttons on heros
![image](https://user-images.githubusercontent.com/4557491/50767343-fecd7d00-12ae-11e9-996a-d148ce067ac6.png)
- [ ]  8.2 check and fix all mobile views: need to do 3 logos in row for mobile view of Partners (2 rows of logos total, not 3). Because not you can't understand what you are reading about, because selected logo is out of the screen. @skkr please alsoo see this and please make opacity difference betwen selected and unselected items more significant
![image](https://user-images.githubusercontent.com/4557491/50767571-f0339580-12af-11e9-8a50-1103d2b1a2cb.png)
- [ ]  8.3 check and fix all mobile views: don't use tabs for mobile view for Features section on main page, see how it's done on current website

- [ ] 9. @skkr let's change style for Features tabs, it's nicer on current website
![image](https://user-images.githubusercontent.com/4557491/51013537-d1b9ec80-1584-11e9-9a23-212d479bb0bd.png)
![image](https://user-images.githubusercontent.com/4557491/51013545-d9799100-1584-11e9-9ad1-971a706b6b71.png)

- [ ] 10. Hero banner on pages: we have to use image, not MDI ICON

**Comment by skkr** [comment]
logo sizes should be proportional, please use the max width setting as in here
https://homepage-dhhuxrbcux.now.sh/#/suppliers

**Good**
![image](https://user-images.githubusercontent.com/1435069/50701136-6ecbd100-102b-11e9-90ae-0cace05b5a33.png)

**Wrong**
![image](https://user-images.githubusercontent.com/1435069/50701164-83a86480-102b-11e9-8dc6-c7d583b870a9.png)

**Comment by menschikov** [comment]
@MatiasOS you made new component "Quotes" for solution page, but did you do that? this should be same component as commons/partnersAndContributors. So we need to reuse one component

but the Quotes is templated in a right way, it has 6 logos
![image](https://user-images.githubusercontent.com/4557491/50736104-63bf9f00-11eb-11e9-9bf4-7b1af04bdfef.png)

Please adjust commons/PartnersAndContributors to look like solutions/Quotes and reuse it on all solution pages. I filled commons/PartnersAndContributors  with real content, please save it while fixing

**Comment by skkr** [comment]
@MatiasOS do it like this:
 
```
<div class="date-box mr-1">27<span class="text-xs">-</span>28<br>Jan</div>
```

![image](https://user-images.githubusercontent.com/1435069/50834363-9cb65b80-1332-11e9-8797-efa7337c1a08.png)


**Before**
![image](https://user-images.githubusercontent.com/1435069/50834285-6547af00-1332-11e9-9bbb-b7afd1ae0631.png)

**Comment by menschikov** [comment]
Created separate tasks for each bug
