### ISSUE TITLE
Banners Header

### ISSUE THREAD

**Issue by menschikov** [windingtree/homepage#190]
**MANDATORY:**

 Hero banner header should be `<H1>` on every page, now we have `<h2>` on all pages except main.
H1 size should be reduced to be as H2, because current h1 doesn't fit small screens.
H2 tag for hero  banners should be replaced with h1

**Comment by skkr** [comment]
**INFO:** use the html elements Alex mentioned, and **h1** to **h6** classes to change their appearance.

`<h1 class="h2">Heading</h1>`
