### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by menschikov** [windingtree/homepage#217]
We need to refactor website to make it's updating and supporting easier, this requires. We must consider that Webpack send all page to same location. We must take care of name overlapping, and use this a benefit to reduce final size. 

1. Splitting code and content: all content should be excluded from components and js files to .json and placed to src/data with the same structure as app elements, e.g.

-src
--data
---commons
---features

2. Proper content-related image handling:
- [ ] Images path should be excluded from "import" and put to .json files together with content data (see point 1.). Image path should be a part of object, e.g. event image path should be stored in event array element field, together with other event data, same for Team, Key benefits and other sections
- [ ] Proper path to images:

-src
--data
---commons/Component_Name/img/
---features/Feature_Name/img/

when deployed webpack should collect all images to e.g /static/img/commons/Component_Name/ or /static/img/commons/Component_Name/

3. Rename folder "Features" to "Pages" to fit human language and remove confusion, e.g. we have **Features**/Home/**Features**

4. Put all static images (logos, bg) to folder /static/img so the path when deployed will be /windingtree.com/img

I think it's worth to start from 3

**Comment by PabloAlice** [comment]
I agree with this proposal.
Just one question about images:
Do we have different image (ie: fixed images, dynamic images, framework images (wt-ui)).
In that case, I would make some changes to this proposal. I don't like the entire path to the img file as 
the img src path

**Comment by menschikov** [comment]
@PabloAlice @MatiasOS please read carefully and pay attention to all issues:

I checked Pablo's structure for refactoring and it's still uncompleted and some of things is unclear

**What was done by Pablo:** 

- created /data folder (in root) with folder for each component with dynamic content (not all components have content e.g card)
- this is still almost empty folder, we have to move data of all components there
![image](https://user-images.githubusercontent.com/4557491/52109701-3adece00-2620-11e9-8c11-475c24f6b3c5.png)
- webpack finds images in this folder and put them to same production folders: /data/path-to-component/path-to-image  e.g. in project folder we put image to /**data**/commons/Events/images/hamburg.png webpack will deploy the image to /_data_/commons/Events/images/hamburg.png
-

**Comment by PabloAlice** [comment]
Relative paths as you want seems not possible.
Webpack can handle that via import statement.
Anyway you will always be structure dependent, even if you don't have change the image page like in your example, you will have to update the component import statement.
Anyway, I get your point, but I don't think it's possible.

Flow types are not logic related. I would keep it there.

I will check what happens with the Events component

**Comment by MatiasOS** [comment]
What about an structure like this?
```
componentName/
- data/
- data/content.json                      // Raw content 
- data/types.flow.js                     // data types declarations
- data/index.js                          // type-checking, mappings 
- index.jsx                              // Component index
- maybeAnotherComponent.jsx
```

**Comment by czervenka** [comment]
Comments from discussion with Alex: This is to separate code and content. Est. finished cca. Wednesday.

**Comment by czervenka** [comment]
Hello, please what is current state of this issue? Is it finished or could you add an estimation?

**Comment by menschikov** [comment]
Completed

**Comment by menschikov** [comment]
Completed
