### ISSUE TITLE
Documention - how to update HP

### ISSUE THREAD

**Issue by czervenka** [windingtree/homepage#251]
As manager I want to be able to change a text on homepage if I have required privileges and basic technical skills.

**Exit criteria:**

- there is a documentation which describes how to update homepage
- anybody with basic technical skills and access rights can make simple changes on homepage (fix typoo, add a simple text)
- there is clear what rights and skills are required

**Comment by czervenka** [comment]
this is a feature request arised on planning meeting with @kvakes and @martinbilek

**Comment by menschikov** [comment]
Who was asking? This story is partially solved with Refactoring, depends what Basic Tech skills means

**Comment by czervenka** [comment]
@martinbilek asked. Could you @menschikov please attach a link to the documentation? I'll ask @martinbilek to try it whether it works for him.

**Comment by menschikov** [comment]
Yes, tomorrow, we need to release refactoring pr and I will update repo readme, it's easy

**Comment by menschikov** [comment]
@czervenka , even when there will be manual, I'll be the one who makes decisions about content. I don't want someone change it without my review.

**Comment by czervenka** [comment]
I added @martinbilek to verify whether he is able to update the site with help of existing documentation.

**Comment by czervenka** [comment]
from planning: @menschikov  is working on that
