### ISSUE TITLE
Direct links to sections

### ISSUE THREAD

**Issue by czervenka** [windingtree/homepage#257]
I would love to have a way to directly point to individual sections on homepage because I want to share them with friends and colleagues.

**Comment by menschikov** [comment]
do you mean link like this https://windingtree.com/Foundation#About ?

**Comment by czervenka** [comment]
I mean any title / sections. It is common (hopefully), that visitors going over our site likes some article or a section and wants to send link to that part to somebody else (over e-mail, chat, ...).

I came to that problem when I wanted to send link to video section and next day when I wanted to ask colleague to look at our road map. I had to send a link to whole website and instructions how to click through the web pages. Is it clear now?

**Comment by menschikov** [comment]
yes)

**Comment by czervenka** [comment]
Looks great, thanks @menschikov
