### ISSUE TITLE
Broken images on lif-token subpage

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/homepage#273]
**Describe the bug**
Images are not shown

**To Reproduce**
1. Go to https://windingtree.com/lif-token

**Screenshots**
![Screenshot_2019-03-13_14-55-46](https://user-images.githubusercontent.com/375483/54284436-3521c400-45a0-11e9-8b87-41e26b964155.png)

**Comment by menschikov** [comment]
@JirkaChadima this page was excluded from menu and we are removing it completely, that's why I updated react library - I edited the footer. We will not have this page until we can provide people clear idea why is it for and how we will use it

**Comment by JirkaChadima** [comment]
OK, didn't know that. I've stumbled upon this link somewhere in the wild.

**Comment by menschikov** [comment]
the only links to there were in footer, now there's no links and no lif page at all

**Comment by JirkaChadima** [comment]
Not on the homepage itself - it was linked from some other page.
