### ISSUE TITLE
MainPage: In the Press

### ISSUE THREAD

**Issue by menschikov** [windingtree/homepage#48]
The In the press section allows only 4 quotes http://joxi.ru/4Ak7qlLTyGknJA
If we have 5, the last one goes out of container to the right
A carousel may work

**Comment by menschikov** [comment]
Desktop version - we have to make sure whote section fits one pc screen
![image](https://user-images.githubusercontent.com/4557491/49057072-e71ac780-f21f-11e8-8510-b612547aee22.png)


mobile
![image](https://user-images.githubusercontent.com/4557491/49057090-f863d400-f21f-11e8-95c0-9f4b94decab4.png)

**Comment by skkr** [comment]
@menschikov , ok, we'll update the design, and the component in wt-ui

**Comment by skkr** [comment]
Reference image

![image](https://user-images.githubusercontent.com/1435069/49758525-efeaaf00-fc9d-11e8-8153-99b851117806.png)

Tab
https://storybook-ef67b.firebaseapp.com/?selectedKind=Navigation&selectedStory=Nav%20Pointers&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel

Blockquote
https://storybook-ef67b.firebaseapp.com/?selectedKind=Typography%2FBlockquotes&selectedStory=Blockquote&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel

Tabbable panes
https://storybook-ef67b.firebaseapp.com/?selectedKind=Containers&selectedStory=Tabbable%20Panes&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel

Logos Gallery
https://storybook-ef67b.firebaseapp.com/?selectedKind=Preset%20Blocks&selectedStory=Logo%20Gallery&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel

**Comment by menschikov** [comment]
nice!

**Comment by menschikov** [comment]
@MatiasOS is it done? I guess yes https://homepage-bafuwceuxb.now.sh/#/home

**Comment by menschikov** [comment]
@skkr please check this section if it's ready. Also think about changing line-height to something larger. Text is hard to read now, here I used "2" http://joxi.ru/GrqbpGlCQWoXRm

**Comment by menschikov** [comment]
seems we need to fix logo sizes that are under tabs block

**Comment by skkr** [comment]
@MatiasOS @PabloAlice can you confirm if we are using the latest version of wt-ui?
