### ISSUE TITLE
typo eReMax to eRevMax

### ISSUE THREAD

**Issue by kvbik** [windingtree/homepage#54]
it is in the scheduled [1] for tomorrow, so we have a bit of time, people will start looking at it>

[1] https://windingtree.com/hacktravel

`eReMax` -> `eRevMax`

**Comment by JirkaChadima** [comment]
Cc @menschikov

**Comment by menschikov** [comment]
Fixed

**Comment by menschikov** [comment]
Guys, that is fixed

ср, 24 окт. 2018 г., 5:41 Jiří Chadima <notifications@github.com>:
