### ISSUE TITLE
FoundationPage build

### ISSUE THREAD

**Issue by MatiasOS** [windingtree/homepage#66]
**Is your feature request related to a problem? Please describe.**
We need to migrate this page to react.

**Describe the solution you'd like**
Foundation page in react.

Order of sections:
1. **Top menu** - requires #144

2. **Hero Banner** - requires #145
Content in JSON
No buttons (empty content)

3. **Intro section**
use current.

4. **Cards block**
as is 

5. **Team & Advisors** - requires #146 

6.  **Video gallery** - requires #90 

7. **Consultation banner** - requires #93 

8. **Roadmap** - requires #142

6. **Events** - requires #96

7. **Subscribe** - requires #87

8. **Ready to use banner** - requires #77

9. **Footer** - requires #143

**Additional context**
live: https://windingtree.com/foundation.html
template: https://github.com/windingtree/homepage/blob/master/foundation.html

**Comment by menschikov** [comment]
We use current layout but replace all old components with redesigned ones
