### ISSUE TITLE
Líf token view

### ISSUE THREAD

**Issue by MatiasOS** [windingtree/homepage#67]
**Is your feature request related to a problem? Please describe.**
We need to migrate this page to react.

**Describe the solution you'd like**
Líf token page in react.

**Describe alternatives you've considered**

**Additional context**
live: https://windingtree.com/lif-token.html

**Comment by menschikov** [comment]
we put it on hold, we deploy website without this page. We need first to describe Lif usage. We need to remove links to this page from menus and footers
