### ISSUE TITLE
CommunityPage build

### ISSUE THREAD

**Issue by MatiasOS** [windingtree/homepage#68]
Is your feature request related to a problem? Please describe.
We need to migrate this page to react.

Describe the solution you'd like
Community token page in react.

Order of sections:
1. **Top menu** - requires #144

2. **Hero Banner** - requires #145
 !important we will have banner with primary button "Join Now"!
social icons not needed here

3. **Max' quote** - requires #95 
Content from JSON
Use current quote

4. **Community banner** - requires #89

5. **Partners** - requires #94 with title "Already with us"

6. **Contributors** - requires #85
Content from JSON

7. **Events** - requires #96

8. **Video gallery** - requires #90
Content from JSON

9. **Subscribe** - requires #87

10. **Ready to use banner** - requires #77

11. **Footer** - requires #143

Additional context
live: https://windingtree.com/startups-and-developers.html

**Comment by menschikov** [comment]
We use current layout but with redesigned components
