### ISSUE TITLE
SellersPage build

### ISSUE THREAD

**Issue by MatiasOS** [windingtree/homepage#71]
**Is your feature request related to a problem? Please describe.**
We need to migrate this page to react.

**Describe the solution you'd like**
Sellers page in react.

Order of sections:
1. **Top menu** - requires #144

2. **Hero Banner** - requires #145
Primary button: Join Platform
Secondary button: Watch Video

3. **Key benefits** - requires #91 
Content can be found here https://docs.google.com/document/d/1spHRz5QpyGWRx00ljAMkF2Ek6AnoQC7Ow-WAaOfBvvQ/edit#heading=h.8ks8u3wzy47

4. **How it Works** - requires #137

6. **Solutions** - requires #92 
Content should be grabbed from json
Purple button: Free integration -> URL
Secondary button: Use cases -> scroll down to Use cases

5. **Partners** - requires #88
Section Header: Use cases

6. **Subscribe** - requires #87
same as for on main page

7. **Ready to use banner** - requires #77
same as for on main page

8. **Footer** - requires #143
same as for on main page

**Additional context**
live: https://windingtree.com/sellers.html

**Comment by menschikov** [comment]
sellers page should be templated in same way as suppliers one #70
