### ISSUE TITLE
VendorsPage build

### ISSUE THREAD

**Issue by MatiasOS** [windingtree/homepage#72]
**Is your feature request related to a problem? Please describe.**
We need to migrate this page to react.

Order of sections:
1. **Top menu** - requires #144

2. **Hero Banner** - requires #145
Content in JSON
Primary button: get on board
Secondary: Watch Video

3. **Intro section**
use current.
Make 2 buttons instead current one:
Primary button: Apply integration
Secondary: Check docs

4. **Cards block**
as is 

5. **How it Works** - requires #137 

6. **Partners** - requires #88
Section Header: Use cases

7. **Subscribe** - requires #87

8. **Ready to use banner** - requires #77

9. **Footer** - requires #143

**Additional context**
live: https://windingtree.com/software-vendors.html

**Comment by menschikov** [comment]
to be consistent we can use same template for vendors as for suppliers #70
