### ISSUE TITLE
New Roadmap

### ISSUE THREAD

**Issue by menschikov** [windingtree/homepage#75]
**Is your feature request related to a problem? Please describe.**
Current roadmap is oblsolete

**Describe the solution you'd like**
need to design and develop new roadmap basing on concept we created

**Describe alternatives you've considered**
leave current layout and will with updated data - temp solution

**Additional context**
https://app.asana.com/0/674097173790718/739430633135490

**Comment by skkr** [comment]
@menschikov new roadmap is in roadmap branch 

https://github.com/windingtree/homepage/tree/roadmap
