### ISSUE TITLE
MainPage build

### ISSUE THREAD

**Issue by MatiasOS** [windingtree/homepage#76]
**Is your feature request related to a problem? Please describe.**
We need to migrate this page to react.

**Describe the solution you'd like**
see current page.

Order of elements:
1. **Top menu** - requires #144 

2. **Hero Banner** - requires #97 + requires #99 
_Primary button:_ Get on Board -> scroll to cards section below (anchor #onboard)
_Secondary button:_ Watch Video
Content for cards can be found here https://docs.google.com/document/d/1spHRz5QpyGWRx00ljAMkF2Ek6AnoQC7Ow-WAaOfBvvQ/edit#heading=h.63dy83a99wh

3. **How it Works** - requires #137 
Additional: add secondary button to the bottom "Watch Video"

4. **Features** - requires #136
Content can be found here: https://docs.google.com/document/d/1spHRz5QpyGWRx00ljAMkF2Ek6AnoQC7Ow-WAaOfBvvQ/edit#heading=h.7u5m6aiw43d0

5. **Partners** - requires #88 + requires #109 
Section header: Partners
Content should be stored in JSON, we use current use cases for: Air NewZeland, Nordic Choices, RSK, Zeppelin - we will have 4 tabs for start but later I will add 2 more.
Don't forget "Become Partner" button after the slick

6. **In the Press** - requires #48 

7. **Community banner** - requires #89 
Content should be stored in JSON: title, description, button label, mdi icon name
Block of social icons is optional to show (true/false)

8. **Video galler**y - requires #90 

9. **Events section** - requires #96 

10. **Subscribe** - requires #87 
temporary save emails to test file

11. **Ready to use banner** - requires #77 
Cards should be same as in Hero Banner and get content from same JSON

12. **Footer** - requires #143

**Additional context**
live: https://windingtree.com/

**Comment by menschikov** [comment]
please pay attention on updated components

**Comment by menschikov** [comment]
Is this a main page?

**Comment by menschikov** [comment]
Requires #144, #97, #99, #136, #137, #88, #109, #48, #89, #90, 96,  #87, #77, #143
