### ISSUE TITLE
AllPages: Ready to use Winding Tree banner

### ISSUE THREAD

**Issue by MatiasOS** [windingtree/homepage#77]
**Is your feature request related to a problem? Please describe.**
Ready to use Winding Tree is used next to the footer in every page. The best approach is have this in only one place. 

**Describe the solution you'd like**
I like to have the component only one time and use it when is required

**Describe alternatives you've considered**
Component must be outside the feature.

**Additional context**
![ready-to-use-windingtree](https://user-images.githubusercontent.com/5481398/48846625-602ca180-ed7e-11e8-933f-5d0eb3344e91.png)

"Cards should be same as in Hero Banner #99 and get content from same JSON"
content for cards  https://docs.google.com/document/d/1spHRz5QpyGWRx00ljAMkF2Ek6AnoQC7Ow-WAaOfBvvQ/edit#heading=h.63dy83a99wh

part of #66 #67 #68 #69 #70 #71 #72
requires #83

**Comment by beogip** [comment]
@MatiasOS I'll take this issue. Please assign me to it

**Comment by menschikov** [comment]
@beogip @MatiasOS if this issue is in development move to that column please

**Comment by beogip** [comment]
@menschikov I do not have permissions to update issues in waffle. This tasks is in development

**Comment by menschikov** [comment]
I will check why. BTW, you can use label "UI in development", it will move
issue to Dev column

вт, 27 нояб. 2018 г., 16:33 Juan Ignacio Gipponi notifications@github.com:

**Comment by beogip** [comment]
The problem's that I'm in `windingtree/wt-collaborators`, this team doesn't have permissions to add labels in this repo

**Comment by menschikov** [comment]
@skkr  please review if UI is finished here
@MatiasOS  this task stuck

**Comment by skkr** [comment]
It can be done using the assets we already have, mainly bootstrap grid classes and [card component](https://storybook-ef67b.firebaseapp.com/?selectedKind=Containers&selectedStory=Card&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel). We also have helpers for [gradient backgrounds](https://storybook-ef67b.firebaseapp.com/?selectedKind=Utilities&selectedStory=Background%20Gradients&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel). Other styles should be custom for the website.

-----
@menschikov , @MatiasOS

**Comment by menschikov** [comment]
Requires #83

**Comment by menschikov** [comment]
@MatiasOS @PabloAlice maybe reassign this tast to Pablo, it has similar cards as in #99, and these cards should get same content from same JSON (See issue description, it's updated)
