### ISSUE TITLE
How it Work Banner

### ISSUE THREAD

**Issue by MatiasOS** [windingtree/homepage#78]
**Is your feature request related to a problem? Please describe.**
This banner is used in Suppliers, Sellers and Software vendros pages. It will be easy to have this code only one time.

**Describe the solution you'd like**
Have this component alone in a common section

**Describe alternatives you've considered**

**Additional context**
![how-it-works](https://user-images.githubusercontent.com/5481398/48850877-61fb6280-ed88-11e8-801c-dbcb51317bd2.png)

part of #70 #71 #72

**Comment by menschikov** [comment]
the illustration will be replaced, illustrator is working on it. I still don't know how it will looks like and what will be mobile view. Maybe it worth to put it on hold until we have new illustration?

**Comment by MatiasOS** [comment]
We will do it how is it now and later we will update

**Comment by menschikov** [comment]
@MatiasOS  there will be no text, just illustration with bg
