### ISSUE TITLE
Change margins

### ISSUE THREAD

**Issue by menschikov** [windingtree/homepage#81]
Nico, I suggest to change paddings for such blocks on homepage, looks much better http://joxi.ru/5mdOqB1TkgJXgr on the screenshot I added +80px to left and right

**Comment by skkr** [comment]
In the latest version of wt-ui margins were set across all app components to keep consistency. We can evaluate this later once we finish the priorities.

**Comment by skkr** [comment]
Related https://github.com/windingtree/homepage/issues/129
