### ISSUE TITLE
Create Card for winding tree banner

### ISSUE THREAD

**Issue by beogip** [windingtree/homepage#83]
**Is your feature request related to a problem? Please describe.**
In issue #77 we need to create a view with several cards. We should avoid repeating code

**Describe the solution you'd like**
I suggest creating a component that receives an image, a text, and a link to avoid repeating code

**Additional context**
<img width="246" alt="screen shot 2018-11-25 at 16 42 12" src="https://user-images.githubusercontent.com/1965274/48983764-a4e37000-f0d1-11e8-8032-32003947c091.png">

**Comment by beogip** [comment]
@MatiasOS and @PabloAlice I'll take this issue

**Comment by menschikov** [comment]
@skkr we will need some components redesigned in Decemenber, I will create task for each component. But I see this card is in production already. We need another type of card to use for the same reasons 
![image](https://user-images.githubusercontent.com/4557491/49055980-7d98ba00-f21b-11e8-9fdd-0f5ea3be08f4.png)

**Comment by menschikov** [comment]
just to let you guys know. @skkr maybe it worth to make UI quickly so @beogip will use it for new card type?

BTW: I want to keep both cards in library! Current card will be still used in pre-footer
![image](https://user-images.githubusercontent.com/4557491/49056078-df592400-f21b-11e8-80bd-c2ec0354b9b4.png)

**Comment by menschikov** [comment]
btw, mobile view of upper hero card will stay a now

**Comment by beogip** [comment]
@menschikov if the current card will be used I think the best it creates another task with the new card, and use this issue to create the component that will be used in the footer. What do you think?

**Comment by menschikov** [comment]
@beogip  how's the process? btw, this is a task for new card #97 it's easy and can be built from standard components
