### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by MatiasOS** [windingtree/homepage#85]
**Is your feature request related to a problem? Please describe.**
We need a component that show contributors of one or more GitHub repositories. 

**Describe the solution you'd like**
We need a component that receives a list of github repositories and show all the contributors.

**Describe alternatives you've considered**

**Additional context**
![contributors](https://user-images.githubusercontent.com/5481398/49006301-8fa92880-f147-11e8-92b1-66b3afd32083.png)

**Comment by skkr** [comment]
Ref: [Storybook](https://storybook-ef67b.firebaseapp.com/?selectedKind=Preset%20Blocks&selectedStory=Devs%20Marquee&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel)

**Comment by menschikov** [comment]
@MatiasOS haven't you finished it??? I guess we discussed it last week
