### ISSUE TITLE
Join

### ISSUE THREAD

**Issue by MatiasOS** [windingtree/homepage#87]
**Is your feature request related to a problem? Please describe.**
We need a join section to use in our sites.

**Describe the solution you'd like**
A component that handle the subscription form and functionality. 

**Describe alternatives you've considered**
It can have a default behavior for the current subscription functionality and receives a function to override it. 

**Additional context**
![join](https://user-images.githubusercontent.com/5481398/49020246-be86c500-f16e-11e8-89b8-6f8618f8525b.png)

Requires #86 
Part of #70 #71 #72

**Comment by menschikov** [comment]
@MatiasOS can you make links opening in new tab?

**Comment by menschikov** [comment]
@skkr we need to fix opacity/color change onHover, onHover effect is almost invisible
