### ISSUE TITLE
MainPage, Sellers, Suppliers, Vendors, Community Page: Use case description (Partners) component 

### ISSUE THREAD

**Issue by menschikov** [windingtree/homepage#88]
**Is your feature request related to a problem? Please describe.**
we need this section to be redesigned to be more attractive
![image](https://user-images.githubusercontent.com/4557491/49057537-dcf9c880-f221-11e8-8356-c2705c24ce75.png)

**Describe the solution you'd like**
A carousel with one use case per view
![image](https://user-images.githubusercontent.com/4557491/49069905-44c50900-f24c-11e8-8d27-c9304b063456.png)
template is similar to Already with us here https://windingtree.com/startups-and-developers.html 

Same with mobile view. 
![image](https://user-images.githubusercontent.com/4557491/49057725-a96b6e00-f222-11e8-8eb5-b20afc88868f.png)

**Describe alternatives you've considered**
best experience

**Additional context**

**Comment by menschikov** [comment]
I would also add some background with rounded corners to the block 
![image](https://user-images.githubusercontent.com/4557491/49058285-31eb0e00-f225-11e8-8ab2-a1bb3aa2f0a5.png)

**Comment by menschikov** [comment]
![image](https://user-images.githubusercontent.com/4557491/49058346-6d85d800-f225-11e8-8779-ab2a9b13f8fb.png)

**Comment by skkr** [comment]
Reference image

![image](https://user-images.githubusercontent.com/1435069/49758827-af3f6580-fc9e-11e8-80d6-2cbdbcdae89e.png)

Tab
https://storybook-ef67b.firebaseapp.com/?selectedKind=Navigation&selectedStory=Nav%20Pointers&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel

Blockquote
https://storybook-ef67b.firebaseapp.com/?selectedKind=Typography%2FBlockquotes&selectedStory=Blockquote&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel

Tabbable panes
https://storybook-ef67b.firebaseapp.com/?selectedKind=Containers&selectedStory=Tabbable%20Panes&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel

Logos Gallery
https://storybook-ef67b.firebaseapp.com/?selectedKind=Preset%20Blocks&selectedStory=Logo%20Gallery&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel
