### ISSUE TITLE
MainPage, CommunityPage: community banner

### ISSUE THREAD

**Issue by menschikov** [windingtree/homepage#89]
Same component as #93 

**Is your feature request related to a problem? Please describe.**
Functionality of this banner should be exptended
![image](https://user-images.githubusercontent.com/4557491/49057885-6362da00-f223-11e8-9989-ccbf0abad246.png)

**Describe the solution you'd like**
**Content should be stored in JSON: title, description, button label, mdi icon name
Block of social icons is optional to show (true/false)**

add tech resources logos with links. Logos should change opacity onhover
![image](https://user-images.githubusercontent.com/4557491/49058129-72965780-f224-11e8-901e-309fd900900a.png)

**Comment by menschikov** [comment]
we have fitting style of social icons on Community page hero
![image](https://user-images.githubusercontent.com/4557491/49070274-18f65300-f24d-11e8-8447-d5550f672550.png)

**Comment by menschikov** [comment]
click on Social icons should open new tab

**Comment by skkr** [comment]
Related to this https://github.com/windingtree/homepage/issues/93
