### ISSUE TITLE
MainPage, CommunityPage: Video section

### ISSUE THREAD

**Issue by menschikov** [windingtree/homepage#90]
**Is your feature request related to a problem? Please describe.**
video section is too big, if doesn't fit one screen on PCs and need to be reduced

**Describe the solution you'd like**
make video section fit one screen. the posible solution can be like here
![image](https://user-images.githubusercontent.com/4557491/50214762-e7336080-03a2-11e9-8fdb-0b844d1de69d.png)

video should open in modal

**Content from JSON!**: captions, titles, urls

**Describe alternatives you've considered**
open for alternatives

**Comment by skkr** [comment]
We can use this for now, component is already in wt-ui.

**Comment by menschikov** [comment]
@skkr  I think if we use current template of gallery - we will have 2 same blocks on page: video gallery and events gallery. What simple solution can you advice?

**Comment by skkr** [comment]
@menschikov depending on how many videos we are going to show,  maybe a grid could work.

We should see how everything works together. Having a wireframe or rough sketch of the full page will help to visualize it better.

**Comment by menschikov** [comment]
![image](https://user-images.githubusercontent.com/4557491/50127952-0348dc00-0295-11e9-80b4-8ca625753c5a.png)

**Comment by skkr** [comment]
@MatiasOS , @PabloAlice , @menschikov 

This section is basically a [grid](https://storybook-ef67b.firebaseapp.com/?selectedKind=Layout%2FGrid&selectedStory=Overview&full=0&addons=0&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel) of [cards with images](https://storybook-ef67b.firebaseapp.com/?selectedKind=Containers&selectedStory=Card&full=0&addons=0&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel). Each "card" will have an image of the video, and `onClick` will open a `.modal-carousel` ([info](https://storybook-ef67b.firebaseapp.com/?selectedKind=Containers%2F%20Modal&selectedStory=Modal%20%28carousel%29&full=0&addons=0&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel))

*To Do*
- [ ] Create a section with grid of card with images ([use this](https://placeholder.com/))
- [ ] Clicking on cards will open a carousel modal
- [ ] Videos must stop playing when changing slides or closing modals

_Let me know when is ready, so I can polish the design of the section._

**Comment by skkr** [comment]
@menschikov [this](https://storybook-ef67b.firebaseapp.com/?selectedKind=Containers%2F%20Modal&selectedStory=Modal%20%28carousel%29&full=0&addons=0&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel)

**Comment by menschikov** [comment]
@skkr we are not doing any carousel here. Just 4 cards with video, onClick - open modal for just one video, no carousel.

**Comment by skkr** [comment]
@menschikov then I misunderstood your screenshots. Anyway is basically the same. Clicking on images should open de `.modal-media` component. And videos should stop on modal close. I'll update tasks in the comment above.

**Comment by menschikov** [comment]
this looks like very simple section we must finish this asap

**Comment by menschikov** [comment]
@MatiasOS, @skkr  there're some issues:

1) title below card should be a link to youtube playlist, each title - different URL. 
e.g. here "About Winding Tree"should be a link and we don't need all videos link
![image](https://user-images.githubusercontent.com/4557491/50476048-70bce100-09e8-11e9-8761-2f0d0bca92e7.png)

or another option could be something like this - Titles should be accented with font, links smaller with less padding between them
![image](https://user-images.githubusercontent.com/4557491/50476095-a792f700-09e8-11e9-962e-44ce29a79c2f.png)
![image](https://user-images.githubusercontent.com/4557491/50476233-415aa400-09e9-11e9-9228-6045cc7b5c4d.png)

@skkr please fix styles
@MatiasOS we need to store URL in JSON object
{
    name: 'Tech Videos',
    href: 'https://www.youtube.com/playlist?list=PLeOExaF4RI3g-o28ogTvKrmeLOy5xo2ev',
    imgSrc: tech,
    videoSrc: 'LHjwNqvLTak',
    url: "some url"
  },

2) We need to overlay images with this button https://commons.wikimedia.org/wiki/File:YouTube_Silver_Play_Button.svg it's not clear that this is a video
3) Cursor should be "pointer" onHover ov image thumbnail

**Comment by skkr** [comment]
@PabloAlice lets go with this one

![image](https://user-images.githubusercontent.com/1435069/50480333-0e4cec00-09ba-11e9-8cf2-f61386b6a76c.png)

**Comment by skkr** [comment]
@MatiasOS If you want I can take care of styling the thumbnails so you can focus on the modals. Let me know what you prefer.
