### ISSUE TITLE
redesign "Solutions" component for Suppliers and Sellers page

### ISSUE THREAD

**Issue by menschikov** [windingtree/homepage#92]
**Is your feature request related to a problem? Please describe.**
current appearance of these components is not attractive, a lot of text

**Describe the solution you'd like**
get rid of unnecessary parts of text and make such component
![image](https://user-images.githubusercontent.com/4557491/49067764-c31eac80-f246-11e8-819b-148273c82b4c.png)

0-2 buttons possible

to use one components per Solution
![image](https://user-images.githubusercontent.com/4557491/49067808-e3e70200-f246-11e8-9af8-ff2272a494f4.png)

**Comment by skkr** [comment]
Related to https://github.com/windingtree/homepage/issues/70

Ref image 
![image](https://user-images.githubusercontent.com/1435069/49759284-ff6af780-fc9f-11e8-9aaa-4fb29cc7801c.png)

**Comment by skkr** [comment]
Related PR:  #130

**Comment by skkr** [comment]
@menschikov , closing this issue since is about redesign and that's done. #70 is the issue still in progress.
