### ISSUE TITLE
FoundationPage: WT services consultation banner

### ISSUE THREAD

**Issue by menschikov** [windingtree/homepage#93]
same component as #89 

**Is your feature request related to a problem? Please describe.**
consultancy banner from Foundation page should be redesigned or removed
![image](https://user-images.githubusercontent.com/4557491/49069658-a0db5d80-f24b-11e8-9eab-a26272386c53.png)

**Describe the solution you'd like**
the banner should be consistent design with other banners we use

**Describe alternatives you've considered**

**Additional context**

**Comment by skkr** [comment]
This can be built by combining components, except for the white box, than can be included in the app directly (we will probably change that, that's why is not in wt-ui)

**Comment by menschikov** [comment]
we need to get rid of that white block and use standard illustration +button template

**Comment by skkr** [comment]
@menschikov if we are going to keep the text and the button I suggest to keep it like this by now, and we can update it later when we have more progress with the illustrations.

**Comment by skkr** [comment]
Otherwise we can use one of these icons
![image](https://user-images.githubusercontent.com/1435069/49230431-68b05800-f3ce-11e8-8f5b-fdb5c44ce1a7.png)
![image](https://user-images.githubusercontent.com/1435069/49230209-e45dd500-f3cd-11e8-8500-b5d8cc2b2961.png)
![image](https://user-images.githubusercontent.com/1435069/49230549-b927b580-f3ce-11e8-892d-8dac288b806f.png)

and this layout
![image](https://user-images.githubusercontent.com/1435069/49230226-ef186a00-f3cd-11e8-8613-b98d5a89153a.png)

**Comment by menschikov** [comment]
last icon and this layout

**Comment by skkr** [comment]
[Ref in Storybook](https://storybook-ef67b.firebaseapp.com/?selectedKind=Layout%2FSections&selectedStory=Section&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel)

**Comment by menschikov** [comment]
@skkr look on the scaling 
![image](https://user-images.githubusercontent.com/4557491/49747907-410e9900-fcc6-11e8-9189-f1739e69b1ce.png)

**Comment by menschikov** [comment]
@MatiasOS this block should be versatile, we will use this banner for different cases (developers banner, WT services etc), so using of this social icon here should be optional (true\false), possible?

**Comment by menschikov** [comment]
if it's too complicated to deal with this icons we can remove them for now and add in future, after website relaunch, that's not a problem at all, it's optional

**Comment by skkr** [comment]
@menschikov I'll take care
