### ISSUE TITLE
CommunityPage: quotes

### ISSUE THREAD

**Issue by menschikov** [windingtree/homepage#95]
**Is your feature request related to a problem? Please describe.**
Max' and Jakub's quotes are of different size and not accented

**Describe the solution you'd like**
We need to reduce Jakub's text
@skkr To attract attention we can add rounded rectangles as bkg for each quote

**Comment by menschikov** [comment]
@skkr we will leave one quote with this template
![image](https://user-images.githubusercontent.com/4557491/49326855-49eec480-f57a-11e8-839f-5132c9785b0a.png)

**Comment by menschikov** [comment]
or this option with video frame - video plays in this frame
![image](https://user-images.githubusercontent.com/4557491/49422164-902f6800-f7b4-11e8-9665-624b2229b420.png)

**Comment by skkr** [comment]
[Blockquote info](https://storybook-ef67b.firebaseapp.com/?selectedKind=Typography%2FBlockquotes&selectedStory=Blockquote&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel)

**Comment by skkr** [comment]
This can be done directly in the website using classes and styles we have already.

We can later make adjustments to the quotes in wr-ui and design library.

**Comment by menschikov** [comment]
I thought you have it in framework we can easily change 20 to 70px, not
involving devs

ср, 19 дек. 2018 г., 18:24 Nico Calabrese notifications@github.com:

**Comment by skkr** [comment]
Yes but is a design decision to change spacing, it should be evaluated properly to be consistent with the design system and not as something isolated. 

By now it can be done easily in the homepage by adding a CSS class.

**Comment by menschikov** [comment]
Please change spacing between quote and signature (from 20 to 70px)

**Comment by menschikov** [comment]
@skkr can you quicky fix it when working with video section on website?

**Comment by menschikov** [comment]
@skkr ?

**Comment by skkr** [comment]
@menschikov increaded the space in the framework directly. I wouldn't make it larger than this. You can [review it here](https://storybook-ef67b.firebaseapp.com/?selectedKind=Typography%2FBlockquotes&selectedStory=Blockquote%20%28card%29&full=0&addons=0&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel).

**Comment by MatiasOS** [comment]
If this not require changes in `@windingtree/homepage`. Can we close it?
