### ISSUE TITLE
AllPages: Event section

### ISSUE THREAD

**Issue by menschikov** [windingtree/homepage#96]
**Is your feature request related to a problem? Please describe.**
Events section is too large and doesn't fit one screen on PC, need to be redesignes

**Describe the solution you'd like**
 like this from https://poa.network/
![image](https://user-images.githubusercontent.com/4557491/49072136-64aafb80-f251-11e8-91d2-a7ea805f9d9f.png)

**Comment by menschikov** [comment]
@skkr we need to make the image frame to store either image or video

**Comment by skkr** [comment]
Ref image

![image](https://user-images.githubusercontent.com/1435069/49758986-207f1880-fc9f-11e8-84dc-52eadb47d92d.png)

**Comment by skkr** [comment]
We have most of what we need to code it so @MatiasOS / @PabloAlice you can start working on it if you need.

It uses tabs, the collapse component, and a grid.

**UI pending**
- [ ] Create a component for date blocks
- [ ] Restyle the default tabs 
- [ ] Evaluate the best way to generate the footer

**Comment by menschikov** [comment]
Nico, please add tab "own events":
Past
Upcoming
Own

**Comment by skkr** [comment]
got it

**Comment by menschikov** [comment]
@PabloAlice fyi

**Comment by skkr** [comment]
@PabloAlice. @menschikov this is ready, new tabs and content can be added at the implementation time

[Ref in Storybook](https://storybook-ef67b.firebaseapp.com/?selectedKind=Templates&selectedStory=Events&full=0&addons=0&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel)

**Comment by menschikov** [comment]
@skkr will we have any description under the image? we need as long as CTA link or button.
 Also Upcoming tab should be first
![image](https://user-images.githubusercontent.com/4557491/50466294-89180600-09be-11e9-8f2d-249ad890f20a.png)

**Comment by skkr** [comment]
@menschikov there is no link, is just like the image posted above, but what I made is a template so is possible to add a link or button. It would be better to have a design ref. but since we don't have much time, lets just resolve it. 

cc @MatiasOS

**Comment by menschikov** [comment]
@skkr just see my initial example on the top

**Comment by skkr** [comment]
Yes, I meant it was not contemplated in the design, but is possible to add a link after the image similar to that example.
