### ISSUE TITLE
MainPage: New card design

### ISSUE THREAD

**Issue by menschikov** [windingtree/homepage#97]
**Is your feature request related to a problem? Please describe.**
current cards are not attractive and contain too much text

**Describe the solution you'd like**
reduce card's visible content
![image](https://user-images.githubusercontent.com/4557491/49092167-37774100-f283-11e8-9ae9-90b5a3fbd845.png)

**Comment by menschikov** [comment]
![image](https://user-images.githubusercontent.com/4557491/49272838-c0b19200-f494-11e8-8b38-ff10057be89c.png)
@skkr let's go simplest way, without slide up text onHover
![image](https://user-images.githubusercontent.com/4557491/49272866-d8891600-f494-11e8-92de-79aa9250f6af.png)

**Comment by menschikov** [comment]
Button label should be variable dependent on cards

**Comment by skkr** [comment]
@menschikov ok, this doesn't require UI work then. It can be done with the assets we already have in wt-ui.

**Comment by skkr** [comment]
Check the info about cards [here](https://storybook-ef67b.firebaseapp.com/?selectedKind=Containers&selectedStory=Card&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel).

**Comment by menschikov** [comment]
@skkr this one fits 
![image](https://user-images.githubusercontent.com/4557491/49776888-d8540a80-fd1f-11e8-8d38-cef9bf8a2efb.png)

but I think there will be too many accented buttons in row of 4-5 cards, maybe it worth to do button outline option?

**Comment by skkr** [comment]
@menschikov that's right, we should use dark outlined buttons.
green buttons are for primary actions, and we sould probably limit its use to one per section

**Comment by skkr** [comment]
[Info about cards](https://storybook-ef67b.firebaseapp.com/?selectedKind=Containers&selectedStory=Card&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel) in Storybook

**Comment by MatiasOS** [comment]
Close because this is resolved in `@windingtree/wt-ui` and `@windingtree/wt-ui-react`
