### ISSUE TITLE
MainPage: Index Banner for main view

### ISSUE THREAD

**Issue by PabloAlice** [windingtree/homepage#99]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Index banner component for the main view
![image](https://user-images.githubusercontent.com/4557491/50267472-24522e00-0449-11e9-813e-d964913cb76f.png)

Button:
Buttons labels and action url should be stored in json
Primary button: Get on Board -> scroll to cards section below (anchor #onboard)
Secondary button: Watch Video

Cards:
We will need 4 cards total.
Make sure content will be grabbed from JSON: image_url, title, description, button label
Content for new cards can be found here: https://docs.google.com/document/d/1spHRz5QpyGWRx00ljAMkF2Ek6AnoQC7Ow-WAaOfBvvQ/edit#heading=h.63dy83a99wh

requires #97 based on #83

**Comment by menschikov** [comment]
@PabloAlice ?

**Comment by menschikov** [comment]
@skkr  please review if UI is finished here

**Comment by skkr** [comment]
@menschikov Is this the hero area in the homepage? Image is still pending but we can base it in the old layout by now and then replace the image and adjust the grid if necessary.

**Comment by menschikov** [comment]
Nico, yes, this is hero for main page

**Comment by skkr** [comment]
@PabloAlice let me know if there is something unclear.

**Comment by menschikov** [comment]
@skkr can you change here button to outline https://storybook-ef67b.firebaseapp.com/?selectedKind=Containers&selectedStory=Card&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel ?

**Comment by menschikov** [comment]
@skkr it's just not to confuse devs. We refer to this stylebook but use outline button on website

**Comment by skkr** [comment]
@menschikov that's right.
